name: TradeShop-ARM
version: ${project.version}
main: org.shanerx.tradeshoparm.TradeShopARM
api-version: 1.14
load: POSTWORLD
depend: [TradeShop, AdvancedRegionMarket]

authors: [Lori00, KillerOfPie]
description: ${project.description}
website: ${project.url}
